# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GymReco' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GymReco
  pod 'SideMenu'
  target 'GymRecoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GymRecoUITests' do
    # Pods for testing
  end

end
